FROM golang:1.21-alpine as builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -o productApp .

FROM alpine
WORKDIR /app
COPY --from=builder /app/productApp .
COPY --from=builder /app/config/config.yml /app/config/config.yml
CMD ["./productApp"]

